### ISSUE TITLE
LGPL3 License (unwanted?) side effects in Go

### ISSUE THREAD

**Issue by cosmos72** [codr7/g-fu#1]
Using LGPL3 license for Go code results in some non-trivial restrictions due to Go using static linking by default and not supporting binary-only packages (see https://github.com/golang/go/issues/28152)

I discussed the effects of LGPL3-ed Go in https://github.com/cosmos72/gomacro/issues/14
In practice, it is almost equivalent to using GPL3 because the exception that you can link a LGPL3 library to a binary with a different license becomes extremely cumbersome to use in Go due to static linking.

Are you willing to consider a different license?

**Comment by codr7** [comment]
You have a point.

I'm quite fed up with licenses, really. They're most probably doing more harm than good from my perspective.

Do you have any objections to Public Domain (https://sqlite.org/copyright.html)?

**Comment by cosmos72** [comment]
Well, *you* could have objections to public domain, and also people potentially contributing to the project.

For my Go projects I chose MPL 2.0 as middle ground between LGPL and MIT, but if you have no problems with public domain, you may as well consider MIT license, which is used by the vast majority of Go projects - including the compiler and standard library

**Comment by codr7** [comment]
Aight, MIT it is then.

https://github.com/codr7/g-fu/commit/09f3ddd8ce7226d4eed968a56aa516fe6269a57e

**Comment by cosmos72** [comment]
You were fast :)
I was wrong: https://github.com/golang/go/blob/master/LICENSE seems to be actually a 3-clause BSD, but for practical purposes BSD and MIT should be basically equivalent:
I definitely remember reading them together as "MIT/BSD" quite often in license discussions for Go, where the writer(s) considered them as equivalent.

**Comment by codr7** [comment]
:)

Like I said, I'm pretty sure by now the whole thing isn't leading anywhere.
If we were to drop all licenses and just let people do more or less
whatever they feel like to public code, I suspect the world would look
mostly the same.

/c7

Den mån 27 maj 2019 kl 17:54 skrev Massimiliano Ghilardi <
notifications@github.com>:
